steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastspring-webhooks', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastspring-webhooks']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastspring-webhooks'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fastspring-webhooks'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SLACK_WEBHOOK_URL=${_SLACK_WEBHOOK_URL},FASTSPRING_HMAC_SECRET=${_FASTSPRING_HMAC_SECRET}'

substitutions:
  _REGION: us-central1
  _SLACK_WEBHOOK_URL: ''
  _FASTSPRING_HMAC_SECRET: ''

images:
  - 'gcr.io/$PROJECT_ID/fastspring-webhooks'
